import { CatchAsyncError } from '../helpers/catchAsyncError.helpers'
import { APIResponse } from '../shared/apiResponse.shared'

export const getAllTasks = CatchAsyncError(async (request, response, next) => {})

